const url = "https://sjachvaecaesin.github.io/wdd230/project/data/vehicles.json";
const metroTitle = document.querySelector("#metro-title");
const metroOcc = document.querySelector("#metro-occ");
const metroReHalf = document.querySelector("#metro-re-half");
const metroReFull = document.querySelector("#metro-re-full");
const metroWaHalf = document.querySelector("#metro-wa-half");
const metroWaFull = document.querySelector("#metro-wa-full");
const dioTitle = document.querySelector("#dio-title");
const dioOcc = document.querySelector("#dio-occ");
const dioReHalf = document.querySelector("#dio-re-half");
const dioReFull = document.querySelector("#dio-re-full");
const dioWaHalf = document.querySelector("#dio-wa-half");
const dioWaFull = document.querySelector("#dio-wa-full");
const pcxTitle = document.querySelector("#pcx-title");
const pcxOcc = document.querySelector("#pcx-occ");
const pcxReHalf = document.querySelector("#pcx-re-half");
const pcxReFull = document.querySelector("#pcx-re-full");
const pcxWaHalf = document.querySelector("#pcx-wa-half");
const pcxWaFull = document.querySelector("#pcx-wa-full");
const pioneerTitle = document.querySelector("#pioneer-title");
const pioneerOcc = document.querySelector("#pioneer-occ");
const pioneerReHalf = document.querySelector("#pioneer-re-half");
const pioneerReFull = document.querySelector("#pioneer-re-full");
const pioneerWaHalf = document.querySelector("#pioneer-wa-half");
const pioneerWaFull = document.querySelector("#pioneer-wa-full");
const fourTitle = document.querySelector("#four-door-title");
const fourOcc = document.querySelector("#four-door-occ");
const fourReHalf = document.querySelector("#four-door-re-half");
const fourReFull = document.querySelector("#four-door-re-full");
const fourWaHalf = document.querySelector("#four-door-wa-half");
const fourWaFull = document.querySelector("#four-door-wa-full");
const twoTitle = document.querySelector("#two-door-title");
const twoOcc = document.querySelector("#two-door-occ");
const twoReHalf = document.querySelector("#two-door-re-half");
const twoReFull = document.querySelector("#two-door-re-full");
const twoWaHalf = document.querySelector("#two-door-wa-half");
const twoWaFull = document.querySelector("#two-door-wa-full");
const rentals = [];

async function getRentals() {
    const response = await fetch(url);
    const data = await response.json();
    displayVehicles(data.rentals);
}

const displayVehicles = (vehicles) => {
    vehicles.forEach((vehicle) => {
        rentals.push(vehicle);
    });
    metroTitle.innerHTML = `${rentals[0].name}`;
    metroOcc.innerHTML = `${rentals[0].occupancy}`;
    metroReHalf.innerHTML = `$${rentals[0].reservehalf}`;
    metroReFull.innerHTML = `$${rentals[0].reservefull}`;
    metroWaHalf.innerHTML = `$${rentals[0].walkhalf}`;
    metroWaFull.innerHTML = `$${rentals[0].walkfull}`;
    dioTitle.innerHTML = `${rentals[1].name}`;
    dioOcc.innerHTML = `${rentals[1].occupancy}`;
    dioReHalf.innerHTML = `$${rentals[1].reservehalf}`;
    dioReFull.innerHTML = `$${rentals[1].reservefull}`;
    dioWaHalf.innerHTML = `$${rentals[1].walkhalf}`;
    dioWaFull.innerHTML = `$${rentals[1].walkfull}`;
    pcxTitle.innerHTML = `${rentals[2].name}`;
    pcxOcc.innerHTML = `${rentals[2].occupancy}`;
    pcxReHalf.innerHTML = `$${rentals[2].reservehalf}`;
    pcxReFull.innerHTML = `$${rentals[2].reservefull}`;
    pcxWaHalf.innerHTML = `$${rentals[2].walkhalf}`;
    pcxWaFull.innerHTML = `$${rentals[2].walkfull}`;
    pioneerTitle.innerHTML = `${rentals[3].name}`;
    pioneerOcc.innerHTML = `${rentals[3].occupancy}`;
    pioneerReHalf.innerHTML = `$${rentals[3].reservehalf}`;
    pioneerReFull.innerHTML = `$${rentals[3].reservefull}`;
    pioneerWaHalf.innerHTML = `$${rentals[3].walkhalf}`;
    pioneerWaFull.innerHTML = `$${rentals[3].walkfull}`;
    fourTitle.innerHTML = `${rentals[4].name}`;
    fourOcc.innerHTML = `${rentals[4].occupancy}`;
    fourReHalf.innerHTML = `$${rentals[4].reservehalf}`;
    fourReFull.innerHTML = `$${rentals[4].reservefull}`;
    fourWaHalf.innerHTML = `$${rentals[4].walkhalf}`;
    fourWaFull.innerHTML = `$${rentals[4].walkfull}`;
    twoTitle.innerHTML = `${rentals[5].name}`;
    twoOcc.innerHTML = `${rentals[5].occupancy}`;
    twoReHalf.innerHTML = `$${rentals[5].reservehalf}`;
    twoReFull.innerHTML = `$${rentals[5].reservefull}`;
    twoWaHalf.innerHTML = `$${rentals[5].walkhalf}`;
    twoWaFull.innerHTML = `$${rentals[5].walkfull}`;
};

getRentals();